type Unit = {
    Id: number;
    Name: string;
    GroupName: string;
    Class: string;
    Variant: string;
    Tonnage: number;
    BattleValue: number;
    Technology: {
        Id: number;
        Name: string;
        Image: null | string;
        SortOrder: number;
    };
    Cost: number;
    Rules: string;
    TROId: number;
    TRO: string;
    RSId: number;
    RS: string;
    EraIcon: string;
    DateIntroduced: string;
    EraId: number;
    EraStart: number;
    ImageUrl: string;
    IsFeatured: boolean;
    IsPublished: boolean;
    Release: number;
    Type: {
        Id: number;
        Name: string;
        Image: string;
        SortOrder: number;
    };
    Role: {
        Id: number;
        Name: string;
        Image: null | string;
        SortOrder: number;
    };
    BFType: string;
    BFSize: number;
    BFMove: string;
    BFTMM: number;
    BFArmor: number;
    BFStructure: number;
    BFThreshold: number;
    BFDamageShort: number;
    BFDamageShortMin: boolean;
    BFDamageMedium: number;
    BFDamageMediumMin: boolean;
    BFDamageLong: number;
    BFDamageLongMin: boolean;
    BFDamageExtreme: number;
    BFDamageExtemeMin: boolean;
    BFOverheat: number;
    BFPointValue: number;
    BFAbilities: string;
    Skill: number;
    FormatedTonnage: string;
    MyId?: number;
    MyDamage?: number;
    MyHeat?: string[];
    MyEngineHits?: number;
    MyFCHits?: number;
    MyMPHits?: number;
    MyWeaponHits?: number;
};

export {};